var Helmet1 = function(){
    document.getElementById("head").src="http://i.imgur.com/fv77tfj.png";
};
var Helmet2 = function(){
    document.getElementById("head").src="http://i.imgur.com/bIyR1PA.png";
};
var Weapon1 = function(){
    document.getElementById("weapon1").src="http://i.imgur.com/nTVwdjT.png"; 
    document.getElementById("weapon2").src="";
};
var Weapon2 = function(){
    document.getElementById("weapon2").src="http://i.imgur.com/je5DhSE.png";
    document.getElementById("weapon1").src="";
};
var Background1 = function(){
    document.getElementById("right").style.backgroundImage="url(http://1.bp.blogspot.com/_r3adJMMRsz0/TP5cs5vsxcI/AAAAAAAAALg/1EtUjUuEmKQ/s1600/110.jpg)";
};
var Background2 = function(){
    document.getElementById("right").style.backgroundImage="url(http://www.cinemablend.com/images/gallery/s24735/star_wars__the_old_republic_12744705077435.jpg)";
};
var Clothing1 = function(){
    document.getElementById("body").src="http://i.imgur.com/Xqy68OI.png";
};
var Clothing2 = function(){
    document.getElementById("body").src="http://i.imgur.com/679Bnya.png";
};